### ISSUE TITLE
Question about visualizing the coupling activation, scale and shift 

### ISSUE THREAD

**Issue by ZhouYuxuanYX** [PolinaKirichenko/flows_ood#3]
Hi,

I have a question about how is the visualization done for these components separately. Since the normalizing flow is a n to n mapping, so dimension reduction is not possible. For example, when visualizing the coupling activation, do you simply substitute the other half dimensions (the branch of calculating scale and shift) with zero?

**Comment by PolinaKirichenko** [comment]
Hi Yuxuan! Lets say that the data dimensionality is n, and x = (x_{change}, x_{id}) is the input to the coupling layer and y = (y_{change}, y_{id}) is the ouptut of the coupling layer where y_{id} = x_{id} and y_{change} = x_{change} * s + t. The scale s and shift t parameters predicted in the coupling layer by a neural network have dimensionality n/2, and we fill in the remaining dimensions with 0s for the shift and 1s for the scale (see [notebook](https://github.com/PolinaKirichenko/flows_ood/blob/master/experiments/notebooks/GLOW_fashion.ipynb) function `draw_st_output`), since it's equivalent to say that the unchanged directions x_{id} are shifted by 0 and scaled by 1. For the visualization of coupling layer output, we plot all dimensions as is (both y_{id} and y_{change}) which would have dimensionality n, please see the same notebook function `draw_coupling_layer`.

Let me know if you have any other questions!
